## Знакомство с библиотекой Pandas

In [2]:
# pandas = panel data
import pandas as pd
from datetime import datetime

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/lesson_2_data.csv',
                 encoding = 'windows-1251',
                 sep = ';')

In [ ]:
# выводим данные
df

,Номер,Дата создания,Дата оплаты,Title,Статус,Заработано,Город,Платежная система
0,1062823,01.12.2019 10:50,01.12.2019 10:52,Курс обучения «Эксперт»,Завершен,29597.50,Чита,Сбербанк эквайринг
1,1062855,01.12.2019 20:53,01.12.2019 21:27,Курс обучения «Эксперт»,Завершен,17450.30,Краснодар,Яндекс.Касса
2,1062856,01.12.2019 21:43,NaN,Курс обучения «Специалист»,Отменен,0.00,NaN,NaN
3,1062880,03.12.2019 0:18,NaN,Курс обучения «Консультант»,Отменен,0.00,г.Москва и Московская область,NaN
4,1062899,03.12.2019 21:43,NaN,Курс обучения «Эксперт»,Отменен,0.00,г.Москва и Московская область,NaN
...,...,...,...,...,...,...,...,...
287,1064720,30.12.2019 9:42,30.12.2019 12:49,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Завершен,2935.44,Самарская область,Яндекс.Касса
288,1064724,30.12.2019 11:32,NaN,Курс обучения «Консультант»,Отменен,0.00,NaN,NaN
289,1064775,31.12.2019 2:17,31.12.2019 2:22,Курс обучения «Консультант»,Завершен,7423.92,NaN,"Сбербанк эквайринг,Бонусный счет"
290,1064793,31.12.2019 16:40,01.01.2020 14:29,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Завершен,2935.44,Республика Карелия,Яндекс.Касса
291,1064796,31.12.2019 17:29,31.12.2019 17:32,Курс от Школы Диетологов. Повышение квалификац...,Завершен,9898.56,Уфа,"Сбербанк эквайринг,Бонусный счет"

In [4]:
# первые 5 строк
df.head()

,Номер,Дата создания,Дата оплаты,Title,Статус,Заработано,Город,Платежная система
0,1062823,01.12.2019 10:50,01.12.2019 10:52,Курс обучения «Эксперт»,Завершен,29597.5,Чита,Сбербанк эквайринг
1,1062855,01.12.2019 20:53,01.12.2019 21:27,Курс обучения «Эксперт»,Завершен,17450.3,Краснодар,Яндекс.Касса
2,1062856,01.12.2019 21:43,NaN,Курс обучения «Специалист»,Отменен,0.0,NaN,NaN
3,1062880,03.12.2019 0:18,NaN,Курс обучения «Консультант»,Отменен,0.0,г.Москва и Московская область,NaN
4,1062899,03.12.2019 21:43,NaN,Курс обучения «Эксперт»,Отменен,0.0,г.Москва и Московская область,NaN

In [5]:
# последние 5 строк
df.tail()

,Номер,Дата создания,Дата оплаты,Title,Статус,Заработано,Город,Платежная система
287,1064720,30.12.2019 9:42,30.12.2019 12:49,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Завершен,2935.44,Самарская область,Яндекс.Касса
288,1064724,30.12.2019 11:32,NaN,Курс обучения «Консультант»,Отменен,0.00,NaN,NaN
289,1064775,31.12.2019 2:17,31.12.2019 2:22,Курс обучения «Консультант»,Завершен,7423.92,NaN,"Сбербанк эквайринг,Бонусный счет"
290,1064793,31.12.2019 16:40,01.01.2020 14:29,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Завершен,2935.44,Республика Карелия,Яндекс.Касса
291,1064796,31.12.2019 17:29,31.12.2019 17:32,Курс от Школы Диетологов. Повышение квалификац...,Завершен,9898.56,Уфа,"Сбербанк эквайринг,Бонусный счет"

In [6]:
# table info
df.shape

(292, 8)

In [7]:
df.dtypes

Номер                  int64
Дата создания         object
Дата оплаты           object
Title                 object
Статус                object
Заработано           float64
Город                 object
Платежная система     object
dtype: object

In [8]:
# basic analytics
df.describe()

              Номер    Заработано
count  2.920000e+02    292.000000
mean   1.063745e+06   3397.615034
std    4.438688e+02   5771.572829
min    1.062823e+06      0.000000
25%    1.063608e+06      0.000000
50%    1.063698e+06   2935.440000
75%    1.063807e+06   2935.440000
max    1.064796e+06  42750.000000

In [9]:
# вызываем все колонки
df.columns

Index(['Номер', 'Дата создания', 'Дата оплаты', 'Title', 'Статус',
       'Заработано', 'Город', 'Платежная система'],
      dtype='object')

In [10]:
# переименование колонок
df = df.rename(columns = {'Номер':'number', 
          'Дата создания':'create_date', 
          'Дата оплаты':'payment_date', 
          'Title':'tittle', 
          'Статус':'status',
          'Заработано':'money', 
          'Город':'city', 
          'Платежная система':'payment_system'})

In [11]:
# выводим один столбец
df['money']

0      29597.50
1      17450.30
2          0.00
3          0.00
4          0.00
         ...
287     2935.44
288        0.00
289     7423.92
290     2935.44
291     9898.56
Name: money, Length: 292, dtype: float64

In [12]:
# выводим два столбца и первые 5 строк
df[['tittle', 'status', 'money']].head()

                        tittle    status    money
0      Курс обучения «Эксперт»  Завершен  29597.5
1      Курс обучения «Эксперт»  Завершен  17450.3
2   Курс обучения «Специалист»   Отменен      0.0
3  Курс обучения «Консультант»   Отменен      0.0
4      Курс обучения «Эксперт»   Отменен      0.0

In [13]:
# выводим столбец
df.status

0      Завершен
1      Завершен
2       Отменен
3       Отменен
4       Отменен
         ...
287    Завершен
288     Отменен
289    Завершен
290    Завершен
291    Завершен
Name: status, Length: 292, dtype: object

In [ ]:
df['money'].head().sum()

47047.8

In [ ]:
# сумма всех денег
all_money = df['money'].sum()

In [ ]:
all_money

992103.5900000001

In [ ]:
# группировка курсов по суммам
df.groupby('tittle', as_index = False).agg({'money':'sum'})

                                              tittle      money
0                        Курс обучения «Консультант»  208163.49
1                         Курс обучения «Специалист»  160862.64
2                            Курс обучения «Эксперт»  148992.80
3                   Курс от Школы Диетологов. Бизнес   18752.54
4  Курс от Школы Диетологов. Повышение квалификац...   88384.92
5  Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...  366947.20

In [14]:
# группировка курсов по суммам и сортировка по сумме по УБЫВАНИЮ (ascending = False)
money_by_city = df  \
    .groupby(['tittle', 'city'], as_index = False) \
    .agg({'money':'sum'}) \
    .sort_values('money', ascending = False)

In [15]:
# сохраняем данные в CSV файл
money_by_city.to_csv('money_by_city.csv', index = False)

In [16]:
money_by_city

,tittle,city,money
51,Курс обучения «Эксперт»,г.Санкт-Петербург и Ленинградская область,59195.00
156,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,г.Москва и Московская область,46967.04
39,Курс обучения «Эксперт»,Балхаш,42750.00
95,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Краснодарский край,38169.78
30,Курс обучения «Специалист»,Краснодар,29695.70
...,...,...,...
63,Курс от Школы Диетологов. Повышение квалификац...,Кемерово,0.00
61,Курс от Школы Диетологов. Повышение квалификац...,Екатеринбург,0.00
55,Курс от Школы Диетологов. Бизнес,Крым Советский,0.00
54,Курс от Школы Диетологов. Бизнес,Киев,0.00
158,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,нижний Новгород,0.00

In [17]:
# группировка курсов по суммам и 
# сортировка по сумме по УБЫВАНИЮ (ascending = False)
# количество заказов > 104620
df  \
    .query('number > 1064620') \
    .groupby(['tittle', 'city'], as_index = False) \
    .agg({'money':'sum', 'number':'count'}) \
    .sort_values('money', ascending = False)

,tittle,city,money,number
7,Курс от Школы Диетологов. Повышение квалификац...,Уфа,9898.56,1
2,Курс обучения «Консультант»,г.Москва и Московская область,8374.82,1
6,Курс от Школы Диетологов. Бизнес,г.Москва и Московская область,5398.56,1
3,Курс обучения «Специалист»,Тамбовская область,3591.84,1
9,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Москва,2935.44,1
10,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Одинцово,2935.44,1
11,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Республика Карелия,2935.44,1
12,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Самарская область,2935.44,1
13,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Тульская область,2935.44,1
1,Курс обучения «Консультант»,София,1.00,1
0,Курс обучения «Консультант»,Свердловская область,0.00,1
4,Курс от Школы Диетологов. Бизнес,Воронежская область,0.00,1
5,Курс от Школы Диетологов. Бизнес,Кемеровская область,0.00,1
8,Курс от Школы Диетологов. Повышение квалификац...,Чеченская Республика,0.00,1

###Способы самопроверки при анализе данных

In [18]:
# Посчитать число успешно (success_orders) завершенных заказов
#---------------------------------------------
# группировка курсов по суммам и 
# сортировка по сумме по УБЫВАНИЮ (ascending = False)
# где status завершен
money_by_tittle = \
      df  \
          .query("status == 'Завершен'") \
          .groupby('tittle', as_index = False) \
          .agg({'money':'sum', 'number':'count'}) \
          .sort_values('money', ascending = False) \
          .rename(columns = {
              'number':'success_orders'
              })

In [19]:
# всего получается 6 успешных курсов
money_by_tittle

,tittle,money,success_orders
5,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,366947.20,125
0,Курс обучения «Консультант»,208163.49,31
1,Курс обучения «Специалист»,160862.64,7
2,Курс обучения «Эксперт»,148992.80,5
4,Курс от Школы Диетологов. Повышение квалификац...,88384.92,9
3,Курс от Школы Диетологов. Бизнес,18752.54,3

In [20]:
# название уникальных курсов
df.tittle.unique()

array(['Курс обучения «Эксперт»', 'Курс обучения «Специалист»',
       'Курс обучения «Консультант»', 'Курс от Школы Диетологов. Бизнес',
       'Курс от Школы Диетологов. Повышение квалификации. ',
       'Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автосписанием'],
      dtype=object)

In [21]:
money_by_tittle.money.sum()

992103.59

In [22]:
all_money

NameError: ignored

In [ ]:
# проверка данных
if(int(money_by_tittle.money.sum()) == int(all_money)):
  print("ok")
else:
  print("ERROR")

ok

## Автоматизация скучной работы

In [23]:
today_day = datetime.today().strftime('%Y-%m-%d')
file_name = ('money_by_tittle_{}.csv')
file_name = file_name.format(today_day)

In [24]:
# проверка данных
if(int(money_by_tittle.money.sum()) == int(all_money)):
  print('OK! File {} is written.'.format(file_name))
  money_by_tittle.to_csv(file_name, index = False)
else:
  print("ERROR")

NameError: ignored

# МИНИПРОЕКТ

In [25]:
import pandas as pd

In [26]:
booking = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/2_bookings.csv',
                  sep = ';')
booking

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

In [27]:
# проверка размера таблицы
booking.shape

(119390, 21)

In [28]:
# выводим первые 7 строк
booking_7 = booking.head(7)
booking_7

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

In [29]:
booking.dtypes

Hotel                         object
Is Canceled                    int64
Lead Time                      int64
arrival full date             object
Arrival Date Year              int64
Arrival Date Month            object
Arrival Date Week Number       int64
Arrival Date Day of Month      int64
Stays in Weekend nights        int64
Stays in week nights           int64
stays total nights             int64
Adults                         int64
Children                     float64
Babies                         int64
Meal                          object
Country                       object
Reserved Room Type            object
Assigned room type            object
customer type                 object
Reservation Status            object
Reservation status_date       object
dtype: object

In [30]:
# какие типы данных преобладают
booking.dtypes.value_counts()

object     10
int64      10
float64     1
dtype: int64

### Задача 2:
#### Преобразование в нижний регистр и в нижний подчеркивания

In [31]:
# создаем небольшую фукнцию для
#    1. преобразование в нижниый регистр: .lower()
#    2. замена пробела в нижниый подчеркивания: .rename()

def replace_space_with_star(name):
    new_name = name \
                    .lower() \
                    .replace(' ', '_')
    return new_name 
booking = booking.rename(columns = replace_space_with_star)
booking

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

### Задача 3:
#### Топ-5 стран по успешным бронированиям

In [32]:
# выводим топ-5 стран по успешным бронированиям

booking_success = booking \
    .query('is_canceled == 0') \
    .groupby('country', as_index = False) \
    .agg({'is_canceled':'count'}) \
    .sort_values('is_canceled', ascending = False) \
    .head(5)

In [33]:
booking_success.rename(columns = {'is_canceled':'success'})

    country  success
125     PRT    21071
57      GBR     9676
54      FRA     8481
50      ESP     6391
42      DEU     6069

In [34]:
# второй вариант и более выгодный вариант через метод value_counts()

booking_success_2 = booking \
        .query('is_canceled == 0') \
        .country \
        .value_counts() \
        .head(5)
booking_success_2

PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
Name: country, dtype: int64

### Задача 4:
#### На сколько ночей в среднем бронируют отели разных типов?

In [35]:
booking.stays_total_nights.sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of 0         0
1         0
2         1
3         1
4         2
         ..
119385    7
119386    7
119387    7
119388    7
119389    9
Name: stays_total_nights, Length: 119390, dtype: int64>

In [36]:
# stays_total_nights (без ROUND)
booking_avg_night = booking \
    .groupby('hotel', as_index = False) \
    .agg({'stays_total_nights':'mean'})

booking_avg_night

          hotel  stays_total_nights
0    City Hotel            2.978142
1  Resort Hotel            4.318547

In [37]:
# stays_total_nights
booking_avg_night_round = round(booking \
    .groupby('hotel', as_index = False) \
    .agg({'stays_total_nights':'mean'}) )

booking_avg_night_round

          hotel  stays_total_nights
0    City Hotel                 3.0
1  Resort Hotel                 4.0

### Задача 5:
#### Иногда тип номера, полученного клиентом (assigned_room_type), отличается от изначально забронированного (reserved_room_type). Такое может произойти, например, по причине овербукинга. Сколько подобных наблюдений встретилось в датасете?

In [38]:
booking.assigned_room_type.value_counts()

A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: assigned_room_type, dtype: int64

In [39]:
booking.reserved_room_type.value_counts()

A    85994
D    19201
E     6535
F     2897
G     2094
B     1118
C      932
H      601
P       12
L        6
Name: reserved_room_type, dtype: int64

In [40]:
# окончательный ответ
booking.query('assigned_room_type != reserved_room_type').reserved_room_type.shape

(14917,)

### Задача 6:
#### Проанализируйте даты запланированного прибытия. – На какой месяц чаще всего успешно оформляли бронь в 2016? Изменился ли самый популярный месяц в 2017?– Сгруппируйте данные по годам и проверьте, на какой месяц бронирования отеля типа City Hotel отменялись чаще всего в каждый из периодов

In [49]:
booking \
    .query('arrival_date_year in (2016,2017)') \
    .groupby(['arrival_date_year', 'arrival_date_month'], as_index = False) \
    .agg({'country':'count'})\
    .sort_values('country', ascending=False)[:2]

    arrival_date_year arrival_date_month  country
19               2017                May     6313
10               2016            October     6176

### Задача 7:
#### Посмотрите на числовые характеристики трёх переменных: adults, children и babies. Какая из них имеет наибольшее среднее значение?

In [99]:
max_mean = booking[['adults', 'children', 'babies']] \
    .mean() \
    .max
max_mean

<bound method NDFrame._add_numeric_operations.<locals>.max of adults      1.856403
children    0.103890
babies      0.007949
dtype: float64>

### Задача 8:
#### Создайте колонку total_kids, объединив children и babies. Для отелей какого типа среднее значение переменной оказалось наибольшим? В качестве ответа укажите наибольшее среднее total_kids, округлив до 2 знаков после точки

In [114]:
booking['total_kids'] = booking['children'] + booking['babies']
max_hotel_by_children = booking \
        .groupby('hotel', as_index = False) \
        .agg({'total_kids':'mean'}) \
        .round(2) \
        .max()
max_hotel_by_children

hotel         Resort Hotel
total_kids            0.14
dtype: object

### Задача 9:
#### Создайте переменную has_kids, которая принимает значение True, если клиент при бронировании указал хотя бы одного ребенка (total_kids), в противном случае – False. Посчитайте отношение количества ушедших пользователей к общему количеству клиентов, выраженное в процентах (churn rate). Укажите, среди какой группы показатель выше.

##### метрика Churn rate

In [115]:
booking['total_kids'] > 0

0         False
1         False
2         False
3         False
4         False
          ...
119385    False
119386    False
119387    False
119388    False
119389    False
Name: total_kids, Length: 119390, dtype: bool

In [116]:
booking['has_kids'] = booking['total_kids'] > 0

In [139]:
# sum_total_kids = booking.total_kids.sum()
# sum_total_kids_is_c_0 = \
#     booking \
#         .query('is_canceled == 0') \
#         .total_kids \
#         .sum()
# churn_rate = (1 - sum_total_kids_is_c_0 / sum_total_kids) * 100
# round (churn_rate, 2)

36.54

In [141]:
churn_rate = \
    round(booking \
          .query('is_canceled == 1 and has_kids == False') \
          .shape[0] \
          / \
          booking \
          .query('has_kids == False') \
          .shape[0] \
          * 100, 2)
churn_rate

37.22